### ISSUE TITLE
Outdated readme and google code site, two areas to update

### ISSUE THREAD

**Issue by jddcef** [StackExchange/StackExchange.DataExplorer#14]
Hi, 

The main page: https://github.com/StackExchange/StackExchange.DataExplorer
mentions the old google code procedure for contributing patches.
Also, the google code site should be updated to mention that the project has moved to github.

Cheers,

David

**Comment by NickCraver** [comment]
I've updated [the Google code page](https://code.google.com/p/stack-exchange-data-explorer/) to simply point here...I thought this was done long ago.  Thanks for the ping and @tms thanks for the README fixes!
