### ISSUE TITLE
SQL Server 2010 does not exist

### ISSUE THREAD

**Issue by win32nipuh** [StackExchange/StackExchange.DataExplorer#75]
https://github.com/StackExchange/StackExchange.DataExplorer

"Prerequisites:
SQL Server 2010 Express or later/higher"

**Comment by mgravell** [comment]
SQL Server 2010 Express does, though:
https://www.microsoft.com/en-gb/download/details.aspx?id=18914

On 22 March 2016 at 13:36, win32nipuh <notifications@github.com> wrote:

> https://github.com/StackExchange/StackExchange.DataExplorer
>
> "Prerequisites:
> SQL Server 2010 Express or later/higher"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.DataExplorer/issues/75>
>



-- 
Regards,

Marc

**Comment by mgravell** [comment]
(I incorrectly posted a wrong link, then nuked it) hmmm, yeah, I wonder which we meant!

**Comment by tms** [comment]
I *probably* meant 2008 R2, but I'll double-check

**Comment by win32nipuh** [comment]
It was "Microsoft **Search Server** 2010 Express", but not SQL Server ;-)

**Comment by NickCraver** [comment]
2012 is minimum on the sane schema, fixed in aedd5fdf6e94f1fd4382e445ecd09e08f3431852
